name: muscu_tracker

description: Application de suivi musculation et nutrition

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.4.5
  video_player_web: ^2.1.0
  sqflite: ^2.0.0+4
  path_provider: ^2.0.8
  intl: ^0.18.1
  shared_preferences: ^2.0.15
  fl_chart: ^0.63.0
  image_picker: ^1.0.4
  flutter_local_notifications: 14.1.1
  permission_handler: ^11.0.1
  google_mlkit_text_recognition: ^0.11.0
  lottie: ^2.6.0
  url_launcher: ^6.2.5
  share_plus: ^7.2.1
  flutter_slidable: ^3.0.0
  pdf: ^3.10.4
  printing: ^5.12.0
  open_file: ^3.2.1
  qr_flutter: ^4.0.0
  flutter_web_auth: # ← pour être reconnu dans le code
  flutter_secure_storage: ^9.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/videos/intro.mp4
    - assets/data/foods.json
    - assets/images/
    - assets/animations/fitness.json
    - assets/animations/nutrition.json
    - assets/animations/history.json

dependency_overrides:
  flutter_web_auth:
    path: lib_plugins/flutter_web_auth/flutter_web_auth-0.5.0
